spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: dev

  application:
    name: crm-project
  mvc:
    pathmatch:
      atching-strategy:
        ant_path_matcher
# MyBatisPlus的相关配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*/*.xml
  global-config:
    #数据库相关配置
    db-config:
      #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一

      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0

      logic-delete-field: is_deleted
      banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /wanshu
  port: 8086
# swagger-ui custom path
springdoc:
  swagger-ui:
    path : /swagger-ui.html
qiniuyun:
  upload:
    # 七牛云访问ak
    accessKey: txVD4rx4HE4YUjI8nvH7T9q6Cdh5JnX-xG2l-HoU
    # 七牛云访问sk
    secretKey: 2Ozn-OlAwGVsk_ZpJGk9vPrPX2ch3WBb5PO6dOkL
    # 你自己创建的空间名
    bucket: myserve12
    # 表示在空间下穿件什么目录存储上传的图片
    mkdir: images/
    # 七牛云分配给你空间的域名
    domain: http://so9r96ky6.hn-bkt.clouddn.com/
